---
# Index Markdown documents only
name: "markdown"
fs:
  url: "/data"

  includes:
    - "*.md"
    - "*.markdown"
  excludes: []
  follow_symlinks: false
  remove_deleted: false
  continue_on_error: false
  index_content: true
  add_filesize: true
  index_folders: true
  checksum: "MD5"
  tika_url: "http://tika:9998"
elasticsearch:
  nodes:
    - url: "http://opensearch:9200"
  ssl_verification: false
  bulk_size: 100
  byte_size: "10mb"
  push_templates: true
rest:
  url: "http://0.0.0.0:8080"
  enable_cors: false
